### ISSUE TITLE
1.3.1 Use Case Diagram

### ISSUE THREAD

**Issue by poh-zun** [aaronlam2000/INF2001_P6-5#1]
High Priority

To do Use Case Diagram

Objective

Complete Use Case Diagram

Success Criteria
- Use case diagram must be clear and concise
- Use case diagram must include the requirements

Start Date: 13th September 2023
End Date: 18th September 2023
Allocated Time: 4 Days

**Comment by sandracsm** [comment]
https://lucid.app/lucidchart/b79e7d3c-6612-4043-a97f-6d0d9cc411d8/edit?invitationId=inv_1a7e4ce3-0fe8-4719-8f9c-d8f12939415f

**Comment by Joo-ooo** [comment]
Completed draft of use case diagram, will further refine it by 19th September 2023



![Image](https://github.com/aaronlam2000/INF2001_P6-5/assets/113295507/f5c6b86b-6f01-4ff0-8408-342452cce968)

**Comment by Joo-ooo** [comment]
Refined Use Case Diagram by assigning one use case to each use bubble instead of putting one functional requirement to one use case bubble. 

![image](https://github.com/aaronlam2000/INF2001_P6-5/assets/113295507/fa3b386a-0496-4d76-8efa-c3d3f496c2ec)

Work was not committed to the repository.

Progress does not affect the deadline.

No changes to the criteria/success of the task.

Start Date: 13th September 2023
End Date: 18th September 2023
