### ISSUE TITLE
Team Meeting 3

### ISSUE THREAD

**Issue by aaronlam2000** [aaronlam2000/INF2001_P6-5#29]
High Priority

Meeting with team to refine report

Objective:
- Refine requirements
- Draft out Activity Diagram
- Arrange client meeting 2
- Write questions for client (focus on non-functional requirements)
- Reformat Kanban board

Success Criteria:
Complete the following objectives stated above

Start Date: 12th September 2023
End Date: 12th September 2023

**Comment by poh-zun** [comment]
Work Done:

- [x] Refine requirements for functional, non-functional, performance, safety and security, and database requirements.
- [x] Drafted out activity diagram.
- [ ] Arrange Client meeting 2
- [x] Write questions for the client
- [x] Reformat Kanban board

Success criteria not met due to:
- No time slot available provided by the client.

Start Date: 12th September 2023
End Date: 12th September 2023
